version: "3.8"  

services:
    solaris:
        build: .
        image: "solaris_ubuntu"
        ports:
            - 8888:8888
            - 6006:6006
        stdin_open: true 
        tty: true
        volumes:
            - ../processedBuildingLabels/data:/home/data